@extends('layouts.onboarding')

@section('title', 'Seu momento · Foundra')

@section('content')
<div class="steps"><div class="step done"></div><div class="step current"></div><div class="step"></div><div class="step"></div></div>
<div class="page-head"><div><div class="eyebrow">Passo 2 de 4</div><h1>Em que momento você está?</h1><p>Usaremos isso para organizar o ponto de partida do seu workspace.</p></div></div>
<form class="form" method="POST" action="{{ route('onboarding.update') }}" novalidate>@csrf @method('PUT')<div class="big-choice">@foreach (['idea' => ['Começando uma ideia', 'Quero descobrir se existe um problema e um público real.'], 'program' => ['Participando de um programa', 'Quero estruturar validação, entrevistas, Canvas e MVP.'], 'post_program' => ['Seguindo após um programa', 'Já tenho materiais e quero continuar a evolução da startup.'], 'mvp' => ['Já tenho MVP ou clientes', 'Quero entender riscos, tração e os próximos passos.']] as $value => [$title, $description])<label class="choice" style="cursor:pointer"><input name="onboarding_stage" type="radio" value="{{ $value }}" style="position:absolute;opacity:0" @checked(old('onboarding_stage', $organization->onboarding_stage) === $value) /><span class="badge {{ $value === 'idea' ? 'primary' : ($value === 'mvp' ? 'success' : '') }}">{{ $value === 'idea' ? 'Recomendado' : 'Seu momento' }}</span><strong style="margin-top:12px">{{ $title }}</strong><p>{{ $description }}</p></label>@endforeach</div>@error('onboarding_stage')<small class="error-msg">{{ $message }}</small>@enderror<div class="card" style="margin-top:18px"><div class="field"><label for="onboarding_goal">O que você quer alcançar agora?</label><input id="onboarding_goal" name="onboarding_goal" value="{{ old('onboarding_goal', $organization->onboarding_goal) }}" placeholder="Ex.: validar se o problema vale ser resolvido" required />@error('onboarding_goal')<small class="error-msg">{{ $message }}</small>@enderror</div></div><div class="actions" style="justify-content:flex-end;margin-top:22px"><a class="btn" href="{{ route('role.select') }}">Voltar</a><button class="btn primary" type="submit">Continuar →</button></div></form>
@endsection
