@extends('layouts.program')

@section('title', 'Turma · Startup Journey')

@section('content')
<div class="page-head"><div><div class="eyebrow">Gestão da Turma</div><h1>Turma Alpha 2027</h1><p>Acompanhe o ritmo do programa sem substituir a autonomia das startups.</p></div><div class="actions"><button class="btn">Editar cronograma</button><button class="btn primary">Adicionar atividade</button></div></div>
<div class="grid four"><div class="card"><div class="metric-label">Startups</div><div class="metric-value">24</div></div><div class="card"><div class="metric-label">Semana</div><div class="metric-value">8/16</div></div><div class="card"><div class="metric-label">Maturidade média</div><div class="metric-value">64%</div></div><div class="card"><div class="metric-label">No caminho certo</div><div class="metric-value">18</div></div></div>
<div class="split wide section"><div><div class="card"><div class="section-head"><h2>Cronograma do Programaa</h2><span class="badge primary">Atual: Validação</span></div><div class="list"><div class="list-item"><div><div class="item-title">Semana 1–2 · Problema Framing</div><div class="item-meta">Concluído</div></div><span class="badge success">Concluído</span></div><div class="list-item"><div><div class="item-title">Semana 3–6 · Descoberta de Clientes</div><div class="item-meta">Concluído</div></div><span class="badge success">Concluído</span></div><div class="list-item"><div><div class="item-title">Semana 7–10 · Validação</div><div class="item-meta">Atual sprint</div></div><span class="badge primary">Now</span></div><div class="list-item"><div><div class="item-title">Semana 11–13 · MVP</div><div class="item-meta">Próximas</div></div><span class="badge">Próximo</span></div><div class="list-item"><div><div class="item-title">Semana 14–16 · Pitch &amp; Demo Day</div><div class="item-meta">Próximas</div></div><span class="badge">Próximas</span></div></div></div><div class="card section"><h2>Progresso por etapa</h2><div class="list"><div class="list-item"><span>Descoberta do Problemaa</span><strong>92%</strong></div><div class="list-item"><span>Descoberta de Clientes</span><strong>78%</strong></div><div class="list-item"><span>Validação</span><strong>61%</strong></div><div class="list-item"><span>MVP</span><strong>28%</strong></div></div></div></div><aside><div class="card warn"><h2>Precisa de atenção</h2><div class="list"><div class="list-item"><span>3 startups inactive for 7+ days</span><span class="badge danger">Risco</span></div><div class="list-item"><span>5 startups have &lt; 5 entrevistas</span><span class="badge warn">Atenção</span></div></div></div><div class="card tint section"><h2>Próximo marco do programa</h2><p>Validação Revisar · Semana 10</p><p style="margin-top:8px">Equipes apresentarão evidências, hipóteses rejeitadas e próximo experimento.</p></div></aside></div>
@endsection
