@extends('layouts.program')

@section('title', 'Painel do Programaa · Startup Journey')

@section('content')
<div class="page-head"><div><div class="eyebrow">Programa workspace</div><h1>Startup Garage 2027</h1><p>Acompanhe evolução, riscos e startups que precisam de atenção.</p></div><div class="actions"><button class="btn">Configurações da turma</button></div></div>
<div class="grid four"><div class="card"><div class="metric-label">Startups ativas</div><div class="metric-value">22</div><div class="metric-sub">of 24</div></div><div class="card"><div class="metric-label">In Validação</div><div class="metric-value">12</div></div><div class="card"><div class="metric-label">MVP</div><div class="metric-value">6</div></div><div class="card"><div class="metric-label">Prontas para apresentação</div><div class="metric-value">4</div></div></div>
<div class="grid two section"><div class="card danger"><div class="section-head"><h2>Startups que precisam de atenção</h2><span class="badge danger">3</span></div><div class="list"><div class="list-item"><div><div class="item-title">FinAI</div><div class="item-meta">Maturidade 62% · Preço not validated</div></div><a class="btn" href="{{ route('program.startup.detail') }}">Ver</a></div><div class="list-item"><div><div class="item-title">EduPulse</div><div class="item-meta">Maturidade 38% · Fraco customer evidências</div></div><a class="btn" href="{{ route('program.startup.detail') }}">Ver</a></div></div></div><div class="card success"><div class="section-head"><h2>Sinais positivos</h2><span class="badge success">4</span></div><div class="list"><div class="list-item"><div><div class="item-title">AgriSense IoT</div><div class="item-meta">MVP pilot · 86% readiness</div></div></div><div class="list-item"><div><div class="item-title">Omnichannel Pay</div><div class="item-meta">3 paid pilots</div></div></div></div></div></div>
<div class="card section"><div class="section-head"><h2>Portfólio de Startups</h2><div class="actions"><button class="btn">Filtrar</button></div></div><table class="table"><thead><tr><th>Startup</th><th>Etapa</th><th>Maturidade</th><th>Última atividade</th><th>Mentor</th><th>Risco</th></tr></thead><tbody><tr><td><strong>FinAI</strong><div class="item-meta">FinTech B2B</div></td><td>Validação</td><td><strong>62%</strong></td><td>Hoje</td><td>Ana Costa</td><td><span class="badge danger">Preço</span></td></tr><tr><td><strong>AgriSense IoT</strong><div class="item-meta">AgriTech</div></td><td>MVP Pilot</td><td><strong>86%</strong></td><td>Hoje</td><td>Marcelo Paiva</td><td><span class="badge success">Baixo</span></td></tr><tr><td><strong>HealthFlow AI</strong><div class="item-meta">HealthTech</div></td><td>Descoberta</td><td><strong>58%</strong></td><td>2 dias atrás</td><td>Camila Valente</td><td><span class="badge warn">Cliente</span></td></tr><tr><td><strong>EduPulse</strong><div class="item-meta">EdTech</div></td><td>Idea</td><td><strong>38%</strong></td><td>4 dias atrás</td><td>—</td><td><span class="badge danger">Evidência</span></td></tr></tbody></table></div>
@endsection
