@extends('layouts.program')

@section('title', 'Programa Mentores · Startup Journey')

@section('content')
<div class="page-head"><div><div class="eyebrow">Rede de Mentores</div><h1>Mentores</h1><p>Acompanhe disponibilidade, especialidades e alocação de mentores.</p></div><div class="actions"><button class="btn primary">＋ Adicionar mentor</button></div></div>
<div class="grid four"><div class="card"><div class="metric-label">Mentores ativos</div><div class="metric-value">12</div></div><div class="card"><div class="metric-label">Mentorias neste mês</div><div class="metric-value">38</div></div><div class="card"><div class="metric-label">Horas alocadas</div><div class="metric-value">142h</div></div><div class="card"><div class="metric-label">Solicitações pendentes</div><div class="metric-value">6</div></div></div>
<div class="grid three section"><div class="card"><div class="item-main"><div class="avatar">AC</div><div><h2>Ana Costa</h2><p>Preço &amp; B2B SaaS</p></div></div><div class="list" style="margin-top:12px"><div class="list-item"><span>Startups</span><strong>4</strong></div><div class="list-item"><span>Allocated</span><strong>24h</strong></div><div class="list-item"><span>Disponibilidade</span><span class="badge success">Disponível</span></div></div></div><div class="card"><div class="item-main"><div class="avatar">MP</div><div><h2>Marcelo Paiva</h2><p>Compliance &amp; FinTech</p></div></div><div class="list" style="margin-top:12px"><div class="list-item"><span>Startups</span><strong>3</strong></div><div class="list-item"><span>Allocated</span><strong>18h</strong></div><div class="list-item"><span>Disponibilidade</span><span class="badge warn">Limitado</span></div></div></div><div class="card"><div class="item-main"><div class="avatar">CV</div><div><h2>Camila Valente</h2><p>Fundraising &amp; GTM</p></div></div><div class="list" style="margin-top:12px"><div class="list-item"><span>Startups</span><strong>5</strong></div><div class="list-item"><span>Allocated</span><strong>16h</strong></div><div class="list-item"><span>Disponibilidade</span><span class="badge success">Disponível</span></div></div></div></div>
@endsection
