@extends('layouts.program')

@section('title', 'Detalhe da Startup · Startup Journey')

@section('content')
<div class="page-head"><div><div class="eyebrow">Startup detail</div><h1>FinAI</h1><p>Visão de acompanhamento para o programa. Dados privados permanecem sob controle do founder.</p></div><div class="actions"><button class="btn">Enviar recomendação</button><button class="btn primary">Solicitar revisão do mentor</button></div></div>
<div class="grid four"><div class="card"><div class="metric-label">Etapa</div><div class="metric-value" style="font-size:22px">Validação</div></div><div class="card"><div class="metric-label">Maturidade</div><div class="metric-value">62%</div></div><div class="card"><div class="metric-label">Evidência</div><div class="metric-value">48</div></div><div class="card"><div class="metric-label">Entrevistas</div><div class="metric-value">12</div></div></div>
<div class="split wide section"><div><div class="card danger"><div class="metric-label">Risco identificado</div><h2>Startup começou a definir MVP antes de validar pricing.</h2><p>Há boa evidência de problema, mas pouca confirmação de disposição a pagar.</p><button class="btn danger" style="margin-top:12px">Enviar recomendação</button></div><div class="card section"><h2>Jornada</h2><div class="timeline"><div class="stage done"><i></i>Idea</div><div class="stage done"><i></i>Descoberta</div><div class="stage current"><i></i>Validação</div><div class="stage"><i></i>MVP</div><div class="stage"><i></i>Mercado</div></div></div><div class="card section"><h2>Atividade recente</h2><div class="list"><div class="list-item"><div><div class="item-title">3 entrevistas analyzed</div><div class="item-meta">Hoje</div></div></div><div class="list-item"><div><div class="item-title">Preço hypothesis updated</div><div class="item-meta">Ontem</div></div></div><div class="list-item"><div><div class="item-title">Mentor recommendation received</div><div class="item-meta">2 dias atrás</div></div></div></div></div></div><aside><div class="card tint"><h2>Mentor feedback</h2><p>“A equipe está progredindo bem em Descoberta de Clientes. O próximo risco é preço.”</p><span class="badge primary" style="margin-top:12px">Ana Costa</span></div><div class="card section"><h2>Visão do programa</h2><p>O gestor vê progresso, riscos e marcos; não altera evidências ou decisões do founder.</p></div></aside></div>
@endsection
