@extends('layouts.mentor')

@section('title', 'Painel do Mentor · Startup Journey')

@section('content')
<div class="page-head"><div><div class="eyebrow">Mentor workspace</div><h1>Bom dia, Ana</h1><p>Veja onde sua orientação pode gerar mais impacto hoje.</p></div><div class="actions"><button class="btn primary">Agendar mentoria</button></div></div>
<div class="grid four"><div class="card"><div class="metric-label">Startups ativas</div><div class="metric-value">4</div></div><div class="card"><div class="metric-label">Feedback pendente</div><div class="metric-value">2</div></div><div class="card"><div class="metric-label">Mentorias this week</div><div class="metric-value">3</div></div><div class="card"><div class="metric-label">Abrir actions</div><div class="metric-value">5</div></div></div>
<div class="grid two section"><div class="card danger"><div class="section-head"><h2>Precisa da sua atenção</h2><span class="badge danger">2</span></div><div class="list"><div class="list-item"><div><div class="item-title">FinAI · Preço hypothesis</div><div class="item-meta">Empreendedor added 3 new entrevistas. Revisar recommended.</div></div><a class="btn" href="{{ route('mentor.startup.detail') }}">Revisar</a></div><div class="list-item"><div><div class="item-title">HealthFlow AI · ICP</div><div class="item-meta">Conflicting evidências detected.</div></div><a class="btn" href="{{ route('mentor.startup.detail') }}">Revisar</a></div></div></div><div class="card"><h2>Próximas mentorias</h2><div class="list"><div class="list-item"><div><div class="item-title">FinAI</div><div class="item-meta">Qui · 15:00 · Preço</div></div><span class="badge primary">Amanhã</span></div><div class="list-item"><div><div class="item-title">AgriSense IoT</div><div class="item-meta">Sex · 10:00 · GTM</div></div><span class="badge">2 days</span></div></div></div></div>
<div class="card section"><h2>Minhas startups</h2><table class="table"><thead><tr><th>Startup</th><th>Etapa</th><th>Desafio atual</th><th>Última atividade</th><th></th></tr></thead><tbody><tr><td><strong>FinAI</strong></td><td>Validação</td><td><span class="badge danger">Preço</span></td><td>Hoje</td><td><a class="btn" href="{{ route('mentor.startup.detail') }}">Abrir</a></td></tr><tr><td><strong>AgriSense IoT</strong></td><td>MVP</td><td><span class="badge warn">GTM</span></td><td>Ontem</td><td><a class="btn" href="{{ route('mentor.startup.detail') }}">Abrir</a></td></tr></tbody></table></div>
@endsection
