@extends('layouts.mentor')

@section('title', 'Startup Revisar · Startup Journey')

@section('content')
<div class="page-head"><div><div class="eyebrow">Revisão do Mentor</div><h1>FinAI</h1><p>Revise evidências, comente hipóteses e sugira experimentos sem assumir decisões pelo founder.</p></div><div class="actions"><button class="btn">Adicionar comentário</button><button class="btn primary">Recommend experiment</button></div></div>
<div class="grid four"><div class="card"><div class="metric-label">Etapa</div><div class="metric-value" style="font-size:22px">Validação</div></div><div class="card"><div class="metric-label">Maturidade</div><div class="metric-value">62%</div></div><div class="card"><div class="metric-label">Evidência</div><div class="metric-value">48</div></div><div class="card"><div class="metric-label">Pendente mentor actions</div><div class="metric-value">2</div></div></div>
<div class="split wide section"><div><div class="card danger"><div class="metric-label">Crítica hypothesis</div><h2>Clientes pagariam R$600/mês.</h2><p>3 evidências contraditórias e apenas 2 sinais favoráveis.</p><div class="tag-row"><span class="badge danger">24% confidence</span><span class="badge">H3 Preço</span></div></div><div class="card section"><h2>Recent evidências</h2><div class="list"><div class="list-item"><span>Interview #12 · price resistance</span><span class="badge danger">Contradiz</span></div><div class="list-item"><span>Interview #11 · willing to test paid pilot</span><span class="badge success">Favorece</span></div><div class="list-item"><span>Interview #10 · needs ROI proof first</span><span class="badge warn">Mista</span></div></div></div></div><aside><div class="card tint"><h2>Sua recomendação</h2><p>Teste três faixas de preço e peça compromisso concreto de piloto, não apenas opinião.</p><div class="actions" style="margin-top:12px"><button class="btn primary">Enviar recomendação</button></div></div><div class="card section"><h2>Permissões do mentor</h2><p>Você pode comentar, sugerir experimentos e revisar marcos. Evidências e decisões permanecem sob controle do founder.</p></div></aside></div>
@endsection
