@extends('layouts.public')

@section('title', 'Foundra — valide antes de construir')

@section('content')
<main class="foundra-home">
    <section class="foundra-intro">
        <nav class="foundra-nav" data-foundra-header aria-label="Navegação principal">
            <a href="{{ route('home') }}" class="foundra-logo" aria-label="Foundra, início"><img src="/logo.png" alt="Foundra"></a>
            <div class="foundra-nav-links"><a href="#metodo">Método</a><a href="#sinais">Sinais</a><a href="#para-quem">Para quem</a></div>
            <div class="foundra-nav-actions"><a href="{{ route('login') }}">Entrar</a><a class="btn btn-primary" href="{{ route('register') }}">Criar conta grátis</a></div>
        </nav>

        <div class="foundra-intro-grid">
            <div class="foundra-intro-copy"><span class="foundra-overline">PARA QUEM ESTÁ CONSTRUINDO O NOVO</span><h1>Construa o que<br>as pessoas <em>precisam.</em></h1><p>A Foundra transforma conversas, hipóteses e testes em uma direção clara para sua startup.</p><div class="foundra-intro-actions"><a class="btn btn-primary btn-lg" href="{{ route('register') }}">Começar minha jornada <span>→</span></a><a href="#metodo">Ver como funciona <span>↓</span></a></div><div class="foundra-intro-note"><i>✓</i> Workspace gratuito para começar. Sem cartão.</div></div>
            <div class="foundra-product-preview" aria-label="Prévia da plataforma Foundra"><div class="preview-topbar"><span class="preview-brand"><i>F</i> Foundra</span><span>⌘ K</span><b>MC</b></div><div class="preview-body"><aside><small>WORKSPACE</small><strong>Nova Mercado</strong><span class="active">Visão geral</span><span>Jornada</span><span>Evidências</span><span>Experimentos</span></aside><div class="preview-main"><header><div><small>BEM-VINDA, MARINA</small><h2>Sua startup em foco.</h2></div><button type="button">＋ Novo teste</button></header><div class="preview-priority"><div><small>PRIORIDADE DA SEMANA</small><strong>Validar a disposição a pagar.</strong><p>3 entrevistas já indicam interesse.</p></div><span>24%</span></div><div class="preview-data"><article><small>PROBLEMA</small><strong>82%</strong><span>✓ Validado</span></article><article><small>CLIENTE</small><strong>71%</strong><span>✓ Em evolução</span></article><article><small>PRÓXIMO PASSO</small><strong>5</strong><span>Entrevistas</span></article></div><div class="preview-activity"><small>ÚLTIMAS EVIDÊNCIAS</small><p><i></i> “Perco horas conciliando vendas no fim do dia.” <span>Hoje</span></p><p><i></i> Novo experimento de preço criado <span>Ontem</span></p></div></div></div></div>
        </div>
        <a class="foundra-scroll-cue" href="#sinais" aria-label="Ir para a próxima seção"><span>Role para explorar</span><i>↓</i></a>
    </section>

    <section class="foundra-statement"><p>STARTUPS NÃO EVOLUEM SÓ POR EXECUTAR.</p><h2>Elas evoluem quando <em>aprendem.</em></h2><div><span>Hipóteses</span><i>+</i><span>Conversas</span><i>+</i><span>Experimentos</span><i>=</i><strong>Direção</strong></div></section>

    <section id="sinais" class="foundra-learning-v2"><div class="learning-v2-copy"><span class="foundra-overline">01 · O SEU CANVAS DE DECISÃO</span><h2>Aprender é ligar os <em>pontos.</em></h2><p>Em vez de guardar descobertas em lugares diferentes, a Foundra mostra como cada conversa muda o que sua startup faz a seguir.</p><div class="learning-v2-list"><div><b>01</b><span><strong>Capture o sinal</strong><small>Registre o que você ouviu e observou.</small></span></div><div><b>02</b><span><strong>Conecte à hipótese</strong><small>Entenda o que essa evidência reforça ou desafia.</small></span></div><div><b>03</b><span><strong>Escolha o próximo teste</strong><small>Transforme contexto em uma ação clara.</small></span></div></div></div><div class="learning-canvas" aria-label="Exemplo de conexão entre evidência, hipótese e decisão"><div class="canvas-top"><span>MAPA DE APRENDIZADO</span><i>⋯</i></div><article class="canvas-conversation"><span>ENTREVISTA COM CLIENTE</span><p>“Eu perderia menos tempo se a conciliação fosse automática.”</p><small>Marina · Lojista</small></article><i class="canvas-line line-one"></i><article class="canvas-hypothesis"><span>HIPÓTESE ATUAL</span><strong>Pequenos lojistas pagam para reduzir trabalho manual.</strong><small>Confiança: em validação</small></article><i class="canvas-line line-two"></i><article class="canvas-decision"><span>PRÓXIMO TESTE</span><strong>Validar disposição a pagar</strong><small>Esta semana <b>→</b></small></article><div class="canvas-badge">1 novo sinal</div></div></section>

    <section class="foundra-scroll-story" data-foundra-story><div class="foundra-scroll-stage"><div class="foundra-scroll-panel" data-foundra-panel><div class="foundra-scroll-orbit orbit-one"></div><div class="foundra-scroll-orbit orbit-two"></div><div class="foundra-scroll-content" data-foundra-story-content><span class="foundra-overline">DO SINAL À DECISÃO</span><h2>O contexto muda<br>tudo.</h2><p>Na Foundra, cada evidência ganha uma conexão. Ao rolar, veja como uma conversa se transforma em direção.</p><div class="foundra-scroll-steps"><span>Entrevista</span><i>→</i><span>Hipótese</span><i>→</i><strong>Decisão</strong></div></div></div></div></section>

    <section id="metodo" class="foundra-method-v2"><div class="method-v2-layout"><header class="method-v2-heading"><span class="foundra-overline">O MÉTODO FOUNDRA</span><h2>Aprenda antes de <em>construir.</em></h2><p>Uma cadência simples para reduzir incertezas sem transformar a jornada em burocracia.</p><a class="method-v2-link" href="{{ route('register') }}">Começar minha jornada <span>→</span></a></header><div class="method-v2-steps"><article><span>01</span><div><small>COMECE AQUI</small><h3>Enquadre</h3><p>Transforme a ideia em uma pergunta que vale investigar.</p></div><i>⌁</i></article><article><span>02</span><div><small>VÁ PARA O CAMPO</small><h3>Escute</h3><p>Converse com quem vive o problema todos os dias.</p></div><i>◌</i></article><article><span>03</span><div><small>REDUZA A INCERTEZA</small><h3>Experimente</h3><p>Teste pequeno antes de construir grande.</p></div><i>↗</i></article><article><span>04</span><div><small>ESCOLHA O CAMINHO</small><h3>Decida</h3><p>Avance, ajuste ou pivote com contexto.</p></div><i>✓</i></article></div></div></section>

    <section id="para-quem" class="foundra-for-v2"><header><span class="foundra-overline">UMA BASE, VÁRIOS OLHARES</span><h2>Um mesmo aprendizado.<br><em>Mais gente alinhada.</em></h2></header><div class="foundra-tabs" data-foundra-tabs><div class="foundra-tab-list" role="tablist" aria-label="Perfis que usam a Foundra"><button type="button" role="tab" aria-selected="true" aria-controls="foundra-founder" id="foundra-founder-tab" data-foundra-tab="foundra-founder">Empreendedores</button><button type="button" role="tab" aria-selected="false" aria-controls="foundra-program" id="foundra-program-tab" data-foundra-tab="foundra-program">Programas</button><button type="button" role="tab" aria-selected="false" aria-controls="foundra-mentor" id="foundra-mentor-tab" data-foundra-tab="foundra-mentor">Mentores</button></div><div class="foundra-tab-panels"><article id="foundra-founder" role="tabpanel" aria-labelledby="foundra-founder-tab" data-foundra-panel-tab><span>01</span><h3>Você não precisa ter todas as respostas para começar.</h3><p>Organize suas descobertas, encontre os riscos reais e avance uma decisão de cada vez.</p><ul><li>Jornada de validação guiada</li><li>Hipóteses e evidências conectadas</li><li>Próximos passos priorizados</li></ul><a class="btn btn-primary" href="{{ route('register') }}">Criar meu workspace →</a></article><article id="foundra-program" role="tabpanel" aria-labelledby="foundra-program-tab" data-foundra-panel-tab hidden><span>02</span><h3>Acompanhe sem transformar acompanhamento em burocracia.</h3><p>Tenha contexto sobre o avanço de cada startup e uma visão clara da sua comunidade.</p><ul><li>Visão por startup e por turma</li><li>Aprendizados rastreáveis</li><li>Mentoria mais contextual</li></ul><a class="btn btn-primary" href="{{ route('register') }}">Conhecer a Foundra →</a></article><article id="foundra-mentor" role="tabpanel" aria-labelledby="foundra-mentor-tab" data-foundra-panel-tab hidden><span>03</span><h3>O melhor feedback começa com a evidência certa.</h3><p>Entre nas conversas sabendo o que já foi testado e qual decisão está em jogo.</p><ul><li>Histórico completo de aprendizado</li><li>Riscos e próximos testes visíveis</li><li>Conversas mais objetivas</li></ul><a class="btn btn-primary" href="{{ route('register') }}">Participar →</a></article></div></div></section>

    <section class="foundra-cta-v2"><div><span class="foundra-overline">A PRÓXIMA EVIDÊNCIA COMEÇA AGORA</span><h2>Menos opinião.<br><em>Mais descoberta.</em></h2></div><div><p>Crie seu workspace e dê à sua startup uma direção baseada no que é real.</p><a class="btn btn-primary btn-lg" href="{{ route('register') }}">Começar gratuitamente <span>→</span></a></div></section>

    <footer class="foundra-footer"><img src="/logo.png" alt="Foundra"><p>Ideias que viram startups baseadas em evidências.</p><small>© {{ now()->year }} Foundra</small></footer>
</main>
@endsection
