@extends('layouts.entrepreneur')

@section('title', 'Concorrentes · Startup Journey')

@section('content')
<div class="page-head"><div><div class="eyebrow">Mercado strategy</div><h1>Cenário Competitivo</h1><p>Compare concorrentes, substitutos e gaps percebidos no mercado.</p></div><div class="actions"><button class="btn">＋ Adicionar concorrente</button><button class="btn primary">✦ Descobrir via IA</button></div></div>
<div class="grid four"><div class="card"><div class="metric-label">Diretos / substitutos</div><div class="metric-value">3</div></div><div class="card"><div class="metric-label">Preço médio de mercado</div><div class="metric-value">R$ 1.075</div></div><div class="card"><div class="metric-label">Tempo médio de implantação</div><div class="metric-value">28 dias</div></div><div class="card"><div class="metric-label">Diferenciação atual</div><div class="metric-value">80%</div></div></div>
<div class="grid three section"><div class="card"><span class="badge">Legacy enterprise</span><h2 style="margin-top:10px">Conciliador Tradicional A</h2><p>Grandes redes e franquias estruturadas.</p><div class="section"><h3>Pontos fortes</h3><p>Robustez, integrações e homologações.</p></div><div class="section"><h3 style="color:var(--danger)">Fragilidade</h3><p>Implantação longa e alto custo.</p></div></div><div class="card"><span class="badge warn">Substituto</span><h2 style="margin-top:10px">Planilhas &amp; templates</h2><p>Pequenos e médios negócios.</p><div class="section"><h3>Pontos fortes</h3><p>Baixo custo e flexibilidade.</p></div><div class="section"><h3 style="color:var(--danger)">Fragilidade</h3><p>Dependência manual e erros.</p></div></div><div class="card"><span class="badge success">Nicho digital</span><h2 style="margin-top:10px">FinPilot</h2><p>E-commerce e marketplaces.</p><div class="section"><h3>Pontos fortes</h3><p>Interface moderna e onboarding rápido.</p></div><div class="section"><h3 style="color:var(--danger)">Fragilidade</h3><p>Pouca aderência ao varejo físico.</p></div></div></div>
<div class="card section"><div class="section-head"><h2>Matriz Comparativa</h2><span class="badge success">5 dimensions</span></div><table class="table"><thead><tr><th>Critério</th><th>FinAI</th><th>Traditional A</th><th>Spreadsheets</th><th>FinPilot</th></tr></thead><tbody><tr><td>Foco em pequenos e médios varejistas</td><td>✓</td><td>—</td><td>✓</td><td>—</td></tr><tr><td>Detecção automática de divergências</td><td>✓</td><td>✓</td><td>—</td><td>—</td></tr><tr><td>Implantação rápida</td><td>✓</td><td>—</td><td>✓</td><td>✓</td></tr><tr><td>Preço acessível</td><td>✓</td><td>—</td><td>✓</td><td>✓</td></tr></tbody></table></div>
<div class="grid two section"><div class="card danger"><h2>Reclamações frequentes</h2><div class="list"><div class="list-item"><span>Complex implementation</span><strong>41 avaliações</strong></div><div class="list-item"><span>Fraco support</span><strong>35 avaliações</strong></div><div class="list-item"><span>Hidden fees</span><strong>28 avaliações</strong></div></div></div><div class="card success"><h2>Oportunidades de mercado</h2><div class="list"><div class="list-item"><div><div class="item-title">Self-service onboarding</div><div class="item-meta">Validado in 18 entrevistas</div></div><span class="badge success">Oportunidade</span></div><div class="list-item"><div><div class="item-title">Multi-acquirer for physical retail</div><div class="item-meta">Recurring pain signal</div></div><span class="badge success">Oportunidade</span></div></div></div></div>
@endsection
