@extends('layouts.entrepreneur')

@section('title', 'Entrevistas · Startup Journey')

@section('content')
<div class="page-head"><div><div class="eyebrow">Cliente discovery</div><h1>Entrevistas com Clientes</h1><p>Aprenda com clientes reais e transforme padrões em evidências.</p></div><div class="actions"><button class="btn">Importararar gravação</button><a class="btn primary" href="{{ route('entrepreneur.interviews.new') }}">＋ Nova entrevista</a></div></div>
<div class="grid four"><div class="card"><div class="metric-label">Concluído</div><div class="metric-value">12</div><div class="metric-sub">Meta: 15</div></div><div class="card"><div class="metric-label">Dor confirmada</div><div class="metric-value">8/12</div></div><div class="card"><div class="metric-label">Usam planilhas</div><div class="metric-value">6/12</div></div><div class="card"><div class="metric-label">Já pagam por alternativas</div><div class="metric-value">4/12</div></div></div>
<div class="card section"><div class="section-head"><h2>Progresso</h2><strong>12 / 15</strong></div><div class="progress success"><span style="width:80%"></span></div></div>
<div class="split wide section"><div><div class="card"><div class="section-head"><div><h2>Marcos Silveira</h2><p>CFO · FarmaNorte</p></div><span class="badge success">Analisado</span></div><div class="grid three"><div><div class="metric-label">Principal aprendizado</div><p>Conciliação ocupa uma manhã por semana.</p></div><div><div class="metric-label">Sinal de compra</div><p>Já paga BPO financeiro.</p></div><div><div class="metric-label">Hipótese</div><p>H1, H3</p></div></div><a class="btn" href="{{ route('entrepreneur.interviews.detail') }}" style="margin-top:14px">Abrir entrevista</a></div>
<div class="card section"><div class="section-head"><div><h2>Mariana Souza</h2><p>Gerente Financeira · Rede Sul</p></div><span class="badge success">Analisado</span></div><div class="grid three"><div><div class="metric-label">Principal aprendizado</div><p>Planilha é mantida por uma pessoa dedicada.</p></div><div><div class="metric-label">Objeção</div><p>Preço acima de R$500 gera resistência.</p></div><div><div class="metric-label">Hipótese</div><p>H1, H3</p></div></div><a class="btn" href="{{ route('entrepreneur.interviews.detail') }}" style="margin-top:14px">Abrir entrevista</a></div></div>
<aside><div class="card tint"><h2>Padrões identificados</h2><div class="list"><div class="list-item"><span>Relatam o problema</span><strong>8/12</strong></div><div class="list-item"><span>Usam Excel</span><strong>6/12</strong></div><div class="list-item"><span>Pagam alternativa</span><strong>4/12</strong></div><div class="list-item"><span>Preço ainda incerto</span><strong style="color:var(--warning)">5/12</strong></div></div><button class="btn primary" style="margin-top:12px">Update hypothesis</button></div></aside></div>
@endsection
