@extends('layouts.entrepreneur')

@section('title', 'Interview Detail · Startup Journey')

@section('content')
<div class="page-head"><div><div class="eyebrow">Cliente interview</div><h1>Marcos Silveira · FarmaNorte</h1><p>48 min · CFO · Rede regional de farmácias</p></div><div class="actions"><a class="btn" href="{{ route('entrepreneur.interviews') }}">← Voltar</a><button class="btn primary">Gerar aprendizados</button></div></div>
<div class="tabs"><div class="tab active">Resumo</div><div class="tab">Transcrição</div><div class="tab">Dores</div><div class="tab">Trechos importantes</div><div class="tab">Hipóteses</div></div>
<div class="split wide"><div><div class="card"><h2>Resumo da IA</h2><p>Marcos confirmou que a conciliação é recorrente, depende de planilhas e costuma ocupar parte significativa da equipe financeira. A empresa já paga por serviços auxiliares, mas mostrou resistência ao preço inicial de R$600/mês.</p></div><div class="card section"><h2>Momentos importantes</h2><div class="list"><div class="list-item"><div><div class="item-title">06:15 · Processo atual</div><div class="item-meta">“Toda sexta-feira alguém precisa fechar as divergências.”</div></div><span class="badge success">Pain</span></div><div class="list-item"><div><div class="item-title">21:40 · Alternativas</div><div class="item-meta">Planilha + conferência manual.</div></div><span class="badge">Solução atual</span></div><div class="list-item"><div><div class="item-title">38:10 · Preço</div><div class="item-meta">R$600 parece alto sem comprovar recuperação.</div></div><span class="badge warn">Objeção</span></div></div></div></div><aside><div class="card"><h2>Hipóteses afetadas</h2><div class="list"><div class="list-item"><span>H1 · Problema frequency</span><span class="badge success">Favorece</span></div><div class="list-item"><span>H2 · Solução atual</span><span class="badge success">Favorece</span></div><div class="list-item"><span>H3 · Preço</span><span class="badge danger">Contradiz</span></div></div></div><div class="card tint section"><h3>Próxima pergunta recomendada</h3><p>Descubra quanto a empresa gasta hoje entre tempo da equipe e serviços auxiliares.</p></div></aside></div>
@endsection
