@extends('layouts.entrepreneur')

@section('title', 'Mentores · Startup Journey')

@section('content')
<div class="page-head"><div><div class="eyebrow">Advisory</div><h1>Mentores e Mentorias</h1><p>Conecte recomendações de especialistas diretamente às hipóteses e próximos passos.</p></div><div class="actions"><button class="btn">＋ Adicionar mentor</button><button class="btn primary">Agendar mentoria</button></div></div>
<div class="grid four"><div class="card"><div class="metric-label">Mentores ativos</div><div class="metric-value">4</div></div><div class="card"><div class="metric-label">Mentorias</div><div class="metric-value">9</div></div><div class="card"><div class="metric-label">Actions completed</div><div class="metric-value">14/17</div></div><div class="card"><div class="metric-label">Feedback pendente</div><div class="metric-value">2</div></div></div>
<div class="split wide section"><div><div class="card tint"><div class="section-head"><div><span class="badge primary">Próximas session</span><h2 style="margin-top:8px">Ana Costa</h2><p>Preço &amp; Monetization</p></div><span class="badge">Qui · 15:00</span></div><div class="section"><div class="metric-label">Tema principal</div><h3>Revisão das entrevistas de disposição a pagar e teste de preço.</h3></div><div class="tag-row"><span class="badge">H3 · Preço</span><span class="badge">H2 · Pain</span></div><div class="actions" style="margin-top:12px"><button class="btn primary">Abrir reunião</button><button class="btn">Ver pauta</button></div></div>
<div class="card section"><div class="section-head"><div><span class="badge success">Concluído</span><h2 style="margin-top:8px">Mentoria #09 · Preço</h2><p>Dr. Marcelo Paiva · 12 Apr · 50 min</p></div></div><div class="card soft"><div class="metric-label">Recomendação</div><p>“Teste três faixas de preço e registre a reação do cliente antes de ampliar o MVP.”</p></div><div class="list" style="margin-top:10px"><div class="list-item"><span>Interview 5 customers</span><span class="badge success">Concluído</span></div><div class="list-item"><span>Run pricing experiment</span><span class="badge warn">Pendente</span></div></div></div></div>
<aside><div class="card"><h2>Mentor bench</h2><div class="list"><div class="list-item"><div class="item-main"><div class="avatar">AC</div><div><div class="item-title">Ana Costa</div><div class="item-meta">FinTech &amp; B2B SaaS</div></div></div><strong>5.0</strong></div><div class="list-item"><div class="item-main"><div class="avatar">MP</div><div><div class="item-title">Marcelo Paiva</div><div class="item-meta">Compliance &amp; Preço</div></div></div><strong>4.9</strong></div><div class="list-item"><div class="item-main"><div class="avatar">CV</div><div><div class="item-title">Camila Valente</div><div class="item-meta">Fundraising</div></div></div><strong>4.8</strong></div></div></div></aside></div>
@endsection
