@extends('layouts.entrepreneur')

@section('title', 'MVP Planner · Startup Journey')

@section('content')
<div class="page-head"><div><div class="eyebrow">Build less, learn faster</div><h1>MVP Planner</h1><p>Construa somente o necessário para testar sua próxima hipótese.</p></div><div class="actions"><button class="btn">Exportarar plan</button><button class="btn primary">Gerar MVP spec</button></div></div>
<div class="card warn"><div class="section-head"><div><div class="metric-label">Recomendação de Validação</div><h2>A hipótese de disposição a pagar ainda possui pouca evidência.</h2><p>Considere validá-la antes de aumentar o escopo.</p></div><span class="badge danger">Preço 24%</span></div></div>
<div class="grid two section"><div class="card"><div class="metric-label">MVP Objective</div><h2>Comprovar se varejistas aceitam pagar por um relatório que identifica divergências.</h2><div class="tag-row"><span class="badge">14 dias</span><span class="badge primary">Hipótese H3</span></div></div><div class="card tint"><div class="metric-label">Métrica de Sucesso</div><div class="metric-value">3 clientes</div><p>Aceitam um piloto remunerado dentro da janela de teste.</p></div></div>
<div class="feature-columns section"><div class="feature-list"><div class="section-head"><h2>Essencial</h2><span class="badge success">Mínimo para testar</span></div><div class="feature"><strong>Enviar arquivo de extrato OFX / CSV</strong><p>Entrada simples de dados reais.</p></div><div class="feature"><strong>Detecção de divergências</strong><p>Regra principal do teste.</p></div><div class="feature"><strong>Relatório PDF</strong><p>Entrega manualmente utilizável.</p></div></div><div class="feature-list"><div class="section-head"><h2>Importararante</h2><span class="badge primary">Depois da validação</span></div><div class="feature"><strong>Painel interativo</strong><p>Pode ser substituído por PDF no piloto.</p></div><div class="feature"><strong>WhatsApp notifications</strong><p>Conveniente, mas não decisivo.</p></div></div><div class="feature-list"><div class="section-head"><h2>Depois</h2><span class="badge warn">Fora do escopo</span></div><div class="feature"><strong>Conciliação de estoque</strong><p>Não necessária para testar preço.</p></div><div class="feature"><strong>15 integrações</strong><p>Alto esforço e pouco aprendizado agora.</p></div><div class="feature"><strong>App nativo</strong><p>Sem valor para a hipótese atual.</p></div></div></div>
<div class="card section tint"><div class="section-head"><div><h2>Recomendação</h2><p>Comece com um piloto operacional e só automatize depois que o cliente confirmar valor.</p></div><span class="badge success">~160h avoided</span></div></div>
@endsection
