@extends('layouts.entrepreneur')

@section('title', 'Novo Interview · Startup Journey')

@section('content')
<div class="page-head"><div><div class="eyebrow">Cliente discovery</div><h1>Novo Interview</h1><p>Registre contexto, gravação e notas para transformar a conversa em evidências.</p></div><div class="actions"><a class="btn" href="{{ route('entrepreneur.interviews') }}">Cancelarar</a><button class="btn primary">Salvar interview</button></div></div>
<div class="grid two"><div class="card"><h2>Entrevistado</h2><form class="form"><div class="field"><label>Nome</label><input value="Carlos Mendes"/></div><div class="field"><label>Empresa</label><input value="Rede Centro"/></div><div class="field"><label>Cargo</label><input value="Gerente Financeiro"/></div><div class="field"><label>Segmentoo</label><select><option>Retail</option><option>FinTech</option><option>Services</option></select></div><div class="field"><label>Data</label><input value="2027-04-18"/></div></form></div><div class="card"><h2>Gravação e anotações</h2><div class="list"><div class="list-item"><div><div class="item-title">Gravação de áudio</div><div class="item-meta">MP3, WAV, M4A</div></div><button class="btn">Enviar arquivo</button></div><div class="list-item"><div><div class="item-title">Gravação de vídeo</div><div class="item-meta">MP4 or meeting recording</div></div><button class="btn">Enviar arquivo</button></div><div class="list-item"><div><div class="item-title">Transcrição</div><div class="item-meta">Paste or import text</div></div><button class="btn">Adicionar</button></div></div><div class="field" style="margin-top:14px"><label>Anotações</label><textarea placeholder="Anote frases, contexto e reações importantes..."></textarea></div></div></div>
<div class="card section tint"><div class="section-head"><div><div class="metric-label">Roteiro sugerido para entrevista</div><h2>Descoberta de Clientes · Problema &amp; Preço</h2></div><span class="badge primary">Com apoio da IA</span></div><div class="list"><div class="list-item"><span>Como você resolve esse problema hoje?</span><span class="badge">01</span></div><div class="list-item"><span>Quando isso aconteceu pela última vez?</span><span class="badge">02</span></div><div class="list-item"><span>Quanto tempo ou dinheiro isso consome?</span><span class="badge">03</span></div><div class="list-item"><span>Você já pagou por alguma solução?</span><span class="badge">04</span></div><div class="list-item"><span>O que faria você trocar a solução atual?</span><span class="badge">05</span></div></div></div>
@endsection
