@extends('layouts.entrepreneur')

@section('title', 'Visão Geral · Startup Journey')

@section('content')
<div class="page-head"><div><div class="eyebrow">Empreendedor workspace</div><h1>FinAI</h1><p>Acompanhe o que já foi provado, o maior risco atual e o próximo passo.</p></div><div class="actions"><button class="btn">＋ Convidar membro</button><button class="btn primary">✦ Perguntar à IA</button></div></div>
<div class="split wide"><div>
<div class="card tint"><div class="section-head"><div><div class="metric-label">Foco Atual</div><h2>Valide se empresas estão dispostas a pagar.</h2><p>Essa é atualmente a hipótese com maior risco.</p></div><span class="badge danger">Preço · 24%</span></div><div class="actions" style="margin-top:14px"><a class="btn primary" href="{{ route('entrepreneur.validation') }}">Criar teste de preço</a><a class="btn" href="{{ route('entrepreneur.research') }}">Ver evidências</a></div></div>
<div class="card section"><div class="section-head"><div><div class="metric-label">Jornada</div><h2>Você está em Validação</h2></div><a class="btn" href="{{ route('entrepreneur.journey') }}">Ver jornada</a></div><div class="timeline"><div class="stage done"><i></i>Idea</div><div class="stage done"><i></i>Descoberta</div><div class="stage current"><i></i>Validação</div><div class="stage"><i></i>Negócio</div><div class="stage"><i></i>MVP</div><div class="stage"><i></i>Mercado</div><div class="stage"><i></i>Tração</div></div></div>
</div><div class="card"><div class="metric-label">Maturidade da Startup</div><div style="display:flex;gap:18px;align-items:center;margin-top:10px"><div class="score-ring" style="--score:62"><strong>62%</strong></div><div><span class="badge primary">Validação</span><p style="margin-top:8px">Baseado em 48 evidências registradas.</p></div></div><div class="list" style="margin-top:12px"><div class="list-item"><div class="item-title">Problema</div><strong>82%</strong></div><div class="list-item"><div class="item-title">Cliente</div><strong>71%</strong></div><div class="list-item"><div class="item-title">Mercado</div><strong>68%</strong></div><div class="list-item"><div class="item-title">Preço</div><strong style="color:var(--danger)">24%</strong></div></div></div></div>
<div class="grid two section"><div class="card"><div class="section-head"><h2>Próximas Ações</h2><span class="badge">3</span></div><div class="list"><div class="list-item"><div class="item-main"><div class="dot primary"></div><div><div class="item-title">Realizar 5 entrevistas</div><div class="item-meta">Descoberta de Clientes</div></div></div><a class="btn" href="{{ route('entrepreneur.interviews') }}">Abrir</a></div><div class="list-item"><div class="item-main"><div class="dot danger"></div><div><div class="item-title">Testar preço</div><div class="item-meta">Hipótese crítica</div></div></div><a class="btn" href="{{ route('entrepreneur.validation') }}">Abrir</a></div><div class="list-item"><div class="item-main"><div class="dot"></div><div><div class="item-title">Analisar concorrente X</div><div class="item-meta">Cenário Competitivo</div></div></div><a class="btn" href="{{ route('entrepreneur.competitors') }}">Abrir</a></div></div></div>
<div class="card"><div class="section-head"><h2>Últimas Evidências</h2><a href="{{ route('entrepreneur.evidence') }}" style="font-size:12px;color:var(--primary);font-weight:800">Ver todas</a></div><div class="list"><div class="list-item"><div class="item-main"><div class="dot success"></div><div><div class="item-title">8/12 lojistas relatam conciliação manual</div><div class="item-meta">Entrevistas · Evidências favoráveis</div></div></div></div><div class="list-item"><div class="item-main"><div class="dot success"></div><div><div class="item-title">27 avaliações reclamam de implantação complexa</div><div class="item-meta">Concorrentes · Evidências favoráveis</div></div></div></div><div class="list-item"><div class="item-main"><div class="dot warn"></div><div><div class="item-title">Preço ainda gera resistência</div><div class="item-meta">3 entrevistas · Contraditória signal</div></div></div></div></div></div></div>
<div class="card section"><div class="section-head"><div><div class="metric-label">Mais recente mentor feedback</div><h2>“Valide o preço antes de aumentar o MVP.”</h2></div><span class="badge primary">Ana Costa</span></div><p>Teste três faixas de preço com clientes que já confirmaram a dor.</p><a class="btn" href="{{ route('entrepreneur.mentors') }}" style="margin-top:12px">Ver mentoria</a></div>
@endsection
