@extends('layouts.entrepreneur')

@section('title', 'Pitch Builder · Startup Journey')

@section('content')
<div class="page-head"><div><div class="eyebrow">Story from evidências</div><h1>Pitch Builder</h1><p>Transforme as evidências da startup em uma narrativa clara.</p></div><div class="actions"><button class="btn">Exportarar PDF</button><a class="btn primary" href="{{ route('entrepreneur.pitch-coach') }}">Practice pitch</a></div></div>
<div class="grid three"><div class="card"><div class="metric-label">Cobertura de evidências</div><div class="metric-value">8/10</div><p>slides supported by evidências</p></div><div class="card"><div class="metric-label">Slides bem sustentados</div><div class="metric-value">6</div></div><div class="card"><div class="metric-label">Precisam de validação</div><div class="metric-value">2</div></div></div>
<div class="pitch-layout section"><div class="slide-list"><div class="slide-item">01 · Problema <span class="badge success" style="float:right">Forte</span></div><div class="slide-item">02 · Evidência <span class="badge success" style="float:right">Forte</span></div><div class="slide-item">03 · Solução <span class="badge info" style="float:right">Médio</span></div><div class="slide-item">04 · Mercado <span class="badge info" style="float:right">Médio</span></div><div class="slide-item active">05 · Tração <span class="badge success" style="float:right">Forte</span></div><div class="slide-item">06 · Business Model <span class="badge warn" style="float:right">Precisa de validação</span></div><div class="slide-item">07 · Competition</div><div class="slide-item">08 · Equipe</div><div class="slide-item">09 · Pedido</div><div class="slide-item">10 · Próximos passos</div></div>
<div><div class="slide-preview"><span class="badge success" style="align-self:flex-start">Sustentado por evidências</span><h1 style="font-size:38px;margin-top:14px">Tração antecipada: validação empírica e disposição a pagar</h1><div class="grid three" style="margin-top:20px"><div class="card"><div class="metric-label">Descoberta de Clientes</div><div class="metric-value">15</div><p>entrevistas</p></div><div class="card"><div class="metric-label">Sinal comercial</div><div class="metric-value">3</div><p>pilotos em negociação</p></div><div class="card"><div class="metric-label">Evidência</div><div class="metric-value">48</div><p>registros</p></div></div></div><div class="card section"><div class="section-head"><div><h2>Evidência links</h2><p>Este slide usa dados já existentes na startup.</p></div><button class="btn">Regenerar texto</button></div><div class="list"><div class="list-item"><span>Interview #12 · FarmaNorte</span><span class="badge success">Verificado</span></div><div class="list-item"><span>Mercado report · Fecomércio</span><span class="badge info">Fonte externa</span></div><div class="list-item"><span>Preço experiment</span><span class="badge warn">Em andamento</span></div></div></div></div></div>
@endsection
