@extends('layouts.entrepreneur')

@section('title', 'Maturidade da Startup · Startup Journey')

@section('content')
<div class="page-head"><div><div class="eyebrow">Pontuação baseada em evidências</div><h1>Maturidade da Startup</h1><p>Entenda o que já foi provado, o que ainda é hipótese e o que fazer agora.</p></div><div class="actions"><button class="btn">Ver methodology</button></div></div>
<div class="split wide"><div class="card tint"><div style="display:flex;align-items:center;gap:24px"><div class="score-ring" style="--score:74"><strong>74%</strong></div><div><span class="badge primary">Validação</span><h2 style="margin-top:9px">Promissora, mas ainda não pronta para o mercado</h2><p>Baseado em 48 evidências registradas e 12 entrevistas.</p></div></div></div><div class="card danger"><div class="metric-label">Principal risco</div><h2>Preço ainda não validado.</h2><p>Você possui sinais de dor, mas pouca evidência de compra.</p><button class="btn danger" style="margin-top:12px">Create pricing experiment</button></div></div>
<div class="grid four section"><div class="card"><div class="metric-label">Problema</div><div class="metric-value">82%</div><span class="badge success">Forte</span></div><div class="card"><div class="metric-label">Cliente</div><div class="metric-value">76%</div></div><div class="card"><div class="metric-label">Mercado</div><div class="metric-value">71%</div></div><div class="card"><div class="metric-label">Solução</div><div class="metric-value">68%</div></div><div class="card"><div class="metric-label">Business Model</div><div class="metric-value">55%</div></div><div class="card"><div class="metric-label">Validação</div><div class="metric-value">62%</div></div><div class="card"><div class="metric-label">MVP</div><div class="metric-value">40%</div></div><div class="card"><div class="metric-label">Tração</div><div class="metric-value">10%</div></div></div>
<div class="grid three section"><div class="card success"><h2>Ponto fortes</h2><div class="list"><div class="list-item"><span>Problemaa recorrente</span><span class="badge success">Forte</span></div><div class="list-item"><span>ICP mais claro</span><span class="badge success">Good</span></div></div></div><div class="card danger"><h2>Riscos</h2><div class="list"><div class="list-item"><span>Preço</span><span class="badge danger">Crítica</span></div><div class="list-item"><span>Diferenciação</span><span class="badge warn">Médio</span></div></div></div><div class="card tint"><h2>Próximo passo recomendado</h2><p>Teste três faixas de preço com 10 potenciais compradores antes de expandir o MVP.</p><button class="btn primary" style="margin-top:12px">Criar experimento</button></div></div>
@endsection
