@extends('layouts.entrepreneur')

@section('title', 'Pesquisa · Startup Journey')

@section('content')
<div class="page-head"><div><div class="eyebrow">Mercado intelligence</div><h1>Pesquisa de Mercado</h1><p>Encontre sinais reais de mercado e conecte-os às hipóteses da startup.</p></div><div class="actions"><span class="badge success">1.428 resultados analisados</span></div></div>
<div class="card"><div style="display:flex;gap:8px"><div class="search" style="max-width:none;flex:1;background:white;border-color:var(--border)">⌕ Pequenos varejistas reclamam de conciliação manual?</div><button class="btn">Filtros</button><button class="btn primary">Pesquisar fontes</button></div><div class="tag-row"><span class="badge">Conciliação manual</span><span class="badge">Taxas ocultas</span><span class="badge">Atraso de repasse</span></div></div>
<div class="tabs section"><div class="tab active">Problemaas</div><div class="tab">Mercado</div><div class="tab">Tendências</div><div class="tab">Comunidades</div><div class="tab">Fontes</div></div>
<div class="split"><div><div class="source-card"><div class="section-head"><div><span class="badge info">Fórum contábil</span> <span class="badge success">Evidência forte</span></div><small class="item-meta">2 dias atrás</small></div><h2>“Pequenos varejistas gastam horas conciliando comprovantes.”</h2><div class="quote">“Todo fim de mês a história é a mesma: extrato do banco, relatório da adquirente e uma planilha que quebra.”</div><div class="tag-row"><span class="badge">H1 · custo de conciliação</span><span class="badge">Relevância 94%</span></div><div class="actions" style="margin-top:12px"><button class="btn">Ver fonte original</button><button class="btn primary">Adicionar como evidência</button></div></div>
<div class="source-card"><div class="section-head"><div><span class="badge">Estudo setorial</span> <span class="badge success">Factual</span></div><small class="item-meta">Q1 2027</small></div><h2>34% dos lojistas analisados relataram cobrança indevida de taxas.</h2><p>Amostra com 512 comércios de varejo e alimentação.</p><div class="tag-row"><span class="badge">H2 · spread oculto</span><span class="badge success">Favorável</span></div><div class="actions" style="margin-top:12px"><button class="btn">Ver estudo</button><button class="btn primary">Adicionar como evidência</button></div></div>
<div class="source-card"><div class="section-head"><div><span class="badge danger">Revisar / reclamação</span></div><small class="item-meta">5 dias atrás</small></div><h2>“O suporte demorou 12 dias para explicar a divergência.”</h2><p>Sinal útil para avaliar alternativas existentes e oportunidades de diferenciação.</p><div class="actions" style="margin-top:12px"><button class="btn">Analisar contexto</button><button class="btn primary">Adicionar como evidência</button></div></div>
</div><aside><div class="card"><h2>Resumo da Pesquisa</h2><div class="list"><div class="list-item"><span>Evidências favoráveis</span><strong style="color:var(--success)">42</strong></div><div class="list-item"><span>Evidências contrárias</span><strong style="color:var(--danger)">13</strong></div><div class="list-item"><span>Inconclusiva</span><strong>18</strong></div></div><div class="progress success" style="margin-top:12px"><span style="width:57%"></span></div><p style="margin-top:8px">57% dos sinais atualmente sustentam as hipóteses.</p></div><div class="card tint section"><h3>Sempre mostramos a fonte original.</h3><p>Nenhuma evidência deve ser aceita sem origem verificável ou contexto suficiente.</p></div></aside></div>
@endsection
